var json=[
    {
        "_id": "foa1143ed59172463d8accd3876ed76dc1",
        "private": false,
        "_type": "Fields::TextField",//类型
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],//子表单
        "choices": [],//单项多项选择
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "单行文字",//标题
        "line_row": 1,//一行一列
        "maximum_length": 0,//最大长度
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,//最小长度
        "notes": "单行文字单行文字单行文字",//提示
        "position": 1,//顺序
        "predefined_value": "单行文字单行文字",//默认文字
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": ['presence','uniqueness']//必填 只读
    },
    {
        "_id": "fo91bfa3ee1ab44c33b72f51dbc46d673c",
        "private": false,
        "_type": "Fields::TextArea",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "多行文字",
        "line_row": 1,
        "maximum_length": 2000,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "多行文字多行文字多行文字",
        "position": 2,
        "predefined_value": "多行文字多行文字",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo1f72a70cdb9f4b47b3dd125d11176486",
        "private": false,
        "_type": "Fields::RadioButton",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [
            {
                "_id": "fo0cdfb4a8186847459e9822b1cde75bdb",
                "_type": "Choice",
                "group": "c19",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "11"
            },
            {
                "_id": "fod014ca13ac0540829f99ab58fe8141c2",
                "_type": "Choice",
                "group": "c19",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "12"
            },
            {
                "_id": "fo350bfece6ace44b5aa2018cc248cc891",
                "_type": "Choice",
                "group": "c19",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "13"
            }
        ],
        "choices_layout": "column",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "单项选择",
        "line_row": 2,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 3,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "11",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "foa9d278ad1f694add849e963ec38eedef",
        "private": false,
        "_type": "Fields::CheckBox",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [
            {
                "_id": "fo8c39776430c74a019838eed6d2d0406b",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "21"
            },
            {
                "_id": "fo6cf545ef38ac45f0a8cd9db2e3ac1015",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "22"
            },
            {
                "_id": "fo14b243e746f149edb4e5a7996d39a96e",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "23"
            },
            {
                "_id": "fob1687770f4684f2c8743986ca59d400f",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "24"
            },
            {
                "_id": "fo45ce878d976c4d08a5b2ccce7861e40e",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "25"
            },
            {
                "_id": "fo51379c8f76c5416fb3b5601b28b14cdc",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "26"
            },
            {
                "_id": "fodbfebece55d545c28de7ecba4541d3af",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "dsf第三方"
            },
            {
                "_id": "fo40bad205be1f4e098866710b50345a0b",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "水电费"
            },
            {
                "_id": "foce4d1924520b4f2586f9a87b851484ce",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "sd"
            },
            {
                "_id": "fofaf7aa7c62514a36ad871c3ec7f8b692",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "sdf收到"
            },
            {
                "_id": "fo59a23c5cd24a499c8856508ee6f06df9",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "dsfsdf"
            },
            {
                "_id": "fo6c35acbbbc6e49a4aeb880014cb4eeb6",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "第三方"
            },
            {
                "_id": "fo3d79a91a395c401e845d2f28629ece68",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "sd"
            },
            {
                "_id": "fo11706562d748464280b91b80a6304359",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "多少"
            },
            {
                "_id": "foa7c2cebb715d4614901663ea275d991d",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "sd sdds的神色"
            },
            {
                "_id": "fo2601cd45a6964ddd8da50983ab44f8e0",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "多少"
            },
            {
                "_id": "fo86bfcffa32344bd39ae6c66c7277a161",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "收到"
            },
            {
                "_id": "fo668e8181a1e74264a5d542e63961f8d0",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "收到"
            },
            {
                "_id": "foa6bd7ade47e349ac97a40ba86963836d",
                "_type": "Choice",
                "group": "c32",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "收到"
            }
        ],
        "choices_layout": "column",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "多项选择",
        "line_row": 3,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 4,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "21",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "foc191699a89b74713bd8a31ba0eab8ca4",
        "private": false,
        "_type": "Fields::DropDown",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [
            {
                "_id": "foac3403dd86b04995afd024195e62caab",
                "_type": "Choice",
                "group": "c77",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "31"
            },
            {
                "_id": "foa065a139dc794aac929952c3dbf5ceaf",
                "_type": "Choice",
                "group": "c77",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "32"
            },
            {
                "_id": "fo54e5c661019c4298bfef12ef256a4951",
                "_type": "Choice",
                "group": "c77",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "33"
            },
            {
                "_id": "fo25d2f46b57df497eb759e4e18eb7916f",
                "_type": "Choice",
                "group": "c77",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "34"
            }
        ],
        "choices_layout": "column",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "下拉框",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 5,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "31",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo7771d6cb24934e56bfe80d0f3ee66534",
        "private": false,
        "_type": "Fields::NumberField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "数字",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "数字数字",
        "position": 6,
        "predefined_value": "数字",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo47c4cae12b65466a8a833dcdd2d70c23",
        "private": false,
        "_type": "Fields::EmailField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "邮箱",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 7,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo4ac1bd0136904f988977271cc613d5ab",
        "private": false,
        "_type": "Fields::TelephoneField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "电话",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "分隔请用-或空格，国际电话请加+",
        "position": 8,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fof2413d1c63fd472c9fc175aa6fad7d98",
        "private": false,
        "_type": "Fields::MobileField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "手机",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 9,
        "predefined_value": "13800138000",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo024e747968e94043b3700a6bb85ef1b2",
        "private": false,
        "_type": "Fields::DateField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "日期",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 10,
        "predefined_value": "2015-10-01",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo7a3ee31fee3d47fcbba63ed0d513107d",
        "private": false,
        "_type": "Fields::TimeField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "时间",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 11,
        "predefined_value": {
            "hour": "06",
            "minute": "07"
        },
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": [],
        "include_second": false
    },
    {
        "_id": "fo1a4f9df0503c430ca29c977824dbfb8f",
        "private": false,
        "_type": "Fields::GeoField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "地理位置",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 12,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo35de2c6fd8b8420ca145753171f86e71",
        "private": false,
        "_type": "Fields::RatingField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [
            {
                "_id": "",
                "_type": "Choice",
                "group": "",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "1"
            },
            {
                "_id": "",
                "_type": "Choice",
                "group": "",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "2"
            },
            {
                "_id": "",
                "_type": "Choice",
                "group": "",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "3"
            },
            {
                "_id": "",
                "_type": "Choice",
                "group": "",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "4"
            },
            {
                "_id": "",
                "_type": "Choice",
                "group": "",
                "quota": "",
                "quota_temp": "",
                "selected": false,
                "sub_choices": [],
                "value": "5"
            }
        ],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "评分",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "1",
        "minimum_length": 0,
        "notes": "",
        "position": 13,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "heart",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo2ae6b718cf6a40688cd5a3608cbe2141",
        "private": false,
        "_type": "Fields::ImageCheckBox",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "side_by_side",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "说明项",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 14,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "focc78634e62a246c89c3834f6e97be3e8",
        "private": false,
        "_type": "Fields::SectionBreak",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 15,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "focd72b8552fd249a9b2ab7fb4fce7f63e",
        "private": false,
        "_type": "Fields::ImageRadioButton",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "side_by_side",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "微信扫码",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 16,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fofebadf60a62a428f90bdad8da7ef36cf",
        "private": false,
        "_type": "Fields::CityField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "省市区",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 17,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo0c81b655a4d8452b9bca7adc485186b2",
        "private": false,
        "_type": "Fields::DateTimeField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "日期时间",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "填写日期时间",
        "position": 18,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo5cd301d9de2f4c8687ee4c651d99bf63",
        "private": false,
        "_type": "Fields::ImageField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "图片",
        "line_row": 1,
        "maximum_length": 0,
        "minimum_grids_to_occupy": "",
        "minimum_length": 0,
        "notes": "",
        "position": 19,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": []
    },
    {
        "_id": "fo163a4467400b4ad8af8846d86a6950ce",
        "private": false,
        "_type": "Fields::ChildField",
        "accurate_num": 4,
        "api_code": "",
        "cache_data": "",
        "childForm": [
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "单行文字单行文字",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fc5c2ef6b79a5f45eb88088ce591033ce7",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "单行文字单行文字单行文字",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "单行文字",
                "type": "TextField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fc8edee96cdd324aa3a160693dcc9b0608",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 2000,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "多行文字",
                "type": "TextArea",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [
                    "121",
                    "122",
                    "123",
                    "124"
                ],
                "default_value": null,
                "end_date": "",
                "group": [
                    false,
                    false,
                    false,
                    false
                ],
                "hour_value": "",
                "id": "fc855ffa3df0f74fdd8289ffff698c4af7",
                "line_row": 1,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [
                    "fc8e47353bbdec4a038f761251bcc69c8a",
                    "fc3b12bd631fcb42118dc8fe37ece04fb6",
                    "fcab929096b044429890fbe9e320d9a4c2",
                    "fc51fdb34a10c9499fb79284b15f42babd"
                ],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "多项选择",
                "type": "CheckBox",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": null,
                "end_date": "",
                "group": [
                    false,
                    false,
                    false
                ],
                "hour_value": "",
                "id": "fc76b1130eb7764e8eb9f43bc22f02a9ff",
                "line_row": 1,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [
                    "fc100ebd9728d943009955cd38db16c994",
                    "fcd0629350eb91482fadf4c87ba34abf8c",
                    "fc36f1caacc71c48b7ad68ad9b4c9012b2"
                ],
                "position": 0,
                "radio": [
                    "131",
                    "132",
                    "133"
                ],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "下拉框",
                "type": "DropDown",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fc850cf4d684e84b91a84ff3bde3698dd2",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 5,
                "min_lengthinput": false,
                "min_value": 3,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "数字",
                "type": "NumberField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fc4e3f6d055f8b45dbb218985efd53bea3",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "邮箱",
                "type": "EmailField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fcc3e3b58bfe6949fbb5c61e092c51c8ab",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "电话",
                "type": "TelephoneField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fc48c3aabe383949cb9bcf9d61245ee151",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "手机",
                "type": "MobileField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "2015-10-02",
                "end_date": "2016-01-09",
                "group": [],
                "hour_value": "",
                "id": "fcb0ef331012ae446487f9bbcc415c8d42",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "2016-01-06",
                "tit_value": "日期",
                "type": "DateField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "02:02",
                "end_date": "",
                "group": [],
                "hour_value": "02",
                "id": "fc373cdfd6541e4b98a1593c6fce64d81e",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "02",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "时间",
                "type": "TimeField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "10",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fc1316a593225b48e39b61745f79576077",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "heart",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "评分",
                "type": "RatingField",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fcedb2310593f546aca05becf56945352e",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [],
                "position": 0,
                "radio": [],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "微信扫码",
                "type": "ImageRadioButton",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": null,
                "end_date": "",
                "group": [
                    false,
                    false,
                    false
                ],
                "hour_value": "",
                "id": "fc49fd24525fe748de883c46ba7a2b6243",
                "line_row": 1,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [
                    "fcd5e5c47e5e354f88821595430780a785",
                    "fcf81d2e9e4dfe46f4aa9359f004d64936",
                    "fc27dcfc0a6a8d4ebd82672692274fe117"
                ],
                "position": 0,
                "radio": [
                    "111",
                    "112",
                    "113"
                ],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "单项选择",
                "type": "RadioButton",
                "valid": ""
            },
            {
                "accurate_num": 0,
                "checkbox": [],
                "default_value": "你愿意成为马猴烧酒吗\n-好啊！\n-你特么才是马猴烧酒，全家都是马猴烧酒\n你大爷的是煞笔\n-煞笔说谁？\n-我这里有脑残片，那去吃",
                "end_date": "",
                "group": [],
                "hour_value": "",
                "id": "fcb33b5a2c1f91430e8fcf3f85a958acee",
                "line_row": 0,
                "max_lengthinput": false,
                "max_value": 0,
                "min_lengthinput": false,
                "min_value": 0,
                "minute_value": "",
                "notes": "",
                "option_ids": [
                    "fc7d632eb9d9f84f749f860fc3dc140b1e",
                    "fcbf8576b54dcc48988dd8a70a076d105d"
                ],
                "position": 0,
                "radio": [
                    "你愿意成为马猴烧酒吗",
                    "你大爷的是煞笔"
                ],
                "rating_type": "",
                "read_only": false,
                "required": false,
                "start_date": "",
                "tit_value": "两级下拉框",
                "type": "CascadeDropDown",
                "valid": ""
            }
        ],
        "choices": [],
        "choices_layout": "",
        "detailHtml": "",
        "editHtml": "",
        "end_date": "",
        "grids_to_occupy": "",
        "has_data": false,
        "label": "这是子表单",
        "line_row": 1,
        "maximum_length": 3,
        "minimum_grids_to_occupy": "",
        "minimum_length": 2,
        "notes": "",
        "position": 20,
        "predefined_value": "",
        "random_choices": false,
        "range_max": "",
        "range_min": "",
        "rating_type": "",
        "selectedChoice": "",
        "start_date": "",
        "start_new_row": "",
        "valid": "",
        "validations": [
            "presence"
        ]
    }
]